### ISSUE TITLE
environment setup docker image can't work

### ISSUE THREAD

**Issue by mina0322** [doraeric/p4-rasp#1]
您好，我是台科大資工的碩班生，目前正在做p4相關的實驗，在看完您的論文後，我嘗試建立您提供的這個p4-rasp專案的http slow attack 實驗，但是在環境建置時遇到了一些問題 😭，想詢問能否用email跟您聯絡請教遇到的問題？
我的email: comiowo22@gmail.com 
可以的話請用這個信箱與我聯絡，非常感謝！

**Comment by doraeric** [comment]
Fixed with b66f068
